/*
main.c: main program. launches whatever necessary data structures
        and calls test functions
Copyright (C) 2019 
maintainer: Carlos WM
email: cwmoreiras@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "main.h"
#include "blockchain.h"
#include "util.h"
#include "linkedlist.h"
#include "dynarray.h"

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <signal.h>
#include <pthread.h>
#include <ev.h>

int main(int argc, char *argv[]) 
// -----------------------------------------------------------------------------
// Func: check command line arguments and start p2p server and client threads
// Args: argc - number of command line arguments
//       argv - command line arguments
// Retn: 0 unless there is an error
// -----------------------------------------------------------------------------
{
  // networking variables
  int lsock, csock;
  struct sockaddr_storage their_addr;
  socklen_t sin_size;
  char s [INET6_ADDRSTRLEN];
  
  int serv_res;
  void *serv_err = 0;
  int threadIndex;

  startup(argc, argv); // handles command line arguments, print license logic
  global_sig_attach(); // attach all signal handlers

  memset(p2p_request, 0, sizeof p2p_request);
  memset(p2p_request, 0, sizeof p2p_thread_table);

  lsock = get_listener_socket(LISTEN_PORT); // get a listener socket 
  if (lsock == -1) {
    perror("main get_listener_socket");
    return -1;
  }

  if (listen(lsock, SERV_BACKLOG) == -1) {
    perror("main listen");
    return -1;
  }
  printf("main: waiting for connections...\n");

  while (1) {
    sin_size = sizeof their_addr;
    csock = accept(lsock, (struct sockaddr *)&their_addr, &sin_size);
    if (csock == -1) {
      perror("p2p_server accept");
      continue;
    }

    inet_ntop(their_addr.ss_family,
      get_in_addr((struct sockaddr *)&their_addr),
      s, sizeof s);
    printf("p2p_server: got connection from %s\n", s);

    // assigning index this way allows us to access all threads (unlike stack)
    // and always assign to the lowest available table slot
    // this line presents a race condition
    threadIndex = p2p_get_thread_index(p2p_thread_table, MAX_CONCURRENT_REQUESTS);    

    // TODO multithreaded server
    if (pthread_create(&p2p_request[threadIndex], NULL, p2p_request_handler, &threadIndex)) {
      fprintf(stderr, "Error creating p2p_server thread\n");
    }
    
  }
  
  // check error codes from joined threads
  if (!(*(int *)serv_err)) {
    printf("p2p_server exit code: %d\n", serv_res);
  }
  else {
    fprintf(stderr, "Error code in p2p_server thread return\n");
  }

  return 0;
}

void *p2p_request_handler(int *threadIndex)
// -----------------------------------------------------------------------------
// Func: server thread of peer to peer service. This thread handles all incoming 
//       data from the connected peers, and responds to queries. It also
//       broadcasts any blocks generated by this node.
// Args: err - a pointer managed by the dispatcher which is used to store error
//             codes for this thread
// Retn: *(int *)err will be zero unless there has been a fault
// -----------------------------------------------------------------------------
{
  pthread_cleanup_push(p2p_request_cleanup, NULL);  
  p2p_thread_table[*threadIndex] = 1;


  pthread_cleanup_pop(1); // run the thread cleanup routine
  pthread_exit(0);
}

void p2p_request_cleanup(int *threadIndex) {
  // empty that slot in the thread table
  p2p_thread_table[*threadIndex] = 0;

}

int get_listener_socket(const char *port) {
  struct addrinfo hints, *servinfo, *p;
  int rv;
  int lsock;
  int yes;
  memset(&hints, 0, sizeof hints);
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_flags = AI_PASSIVE;

  if ((rv = getaddrinfo(NULL, port, &hints, &servinfo)) != 0) {
    fprintf(stderr, " p2p_server getaddrinfo: %s\n", gai_strerror(rv));
    return -1;
  }

  for (p = servinfo; p != NULL; p = p->ai_next) {
    if ((lsock = socket(p->ai_family, p->ai_socktype, 
      p->ai_protocol)) == -1) {
        perror("p2p_server: socket");
        continue;
    }
    if (setsockopt(lsock, SOL_SOCKET, SO_REUSEADDR, &yes, 
      sizeof(int)) == -1) {
        perror("p2p_server setsockopt");
        return -1;
    }
    if (bind(lsock, p->ai_addr, p->ai_addrlen) == -1) {
      close(lsock);
      perror("p2p_server: bind");
      continue;
    }
    break;
  }
  freeaddrinfo(servinfo);
  
  if (p == NULL) {
    fprintf(stderr, "p2p_server: failed to bind\n");
    return -1;
  }

  return lsock;
}

int p2p_get_thread_index(int *table, int sz) {
  int i;

  for (i = 0; i < sz; i++) {
    if(table[i] == 0) {
      return i;
    }

  }

  return -1;
}

void *get_in_addr(struct sockaddr *sa) 
{
  return sa->sa_family == AF_INET
    ? (void *) &(((struct sockaddr_in*)sa)->sin_addr)
    : (void *) &(((struct sockaddr_in6*)sa)->sin6_addr);
}

int global_sig_attach(void) {
  struct sigaction child_action;
  struct sigaction int_action; // normal way to shut down server

  // right now we're not multiprocessing
  child_action.sa_handler = sigchld_handler; // bury zombie processes
  sigemptyset(&child_action.sa_mask);
  child_action.sa_flags = SA_RESTART;
  if (sigaction(SIGCHLD, &child_action, NULL) == -1) {
    perror("sigaction SIGCHLD");
    return -1;
  } 

  // TODO sigint should be normal way to shut down cleanly
  /*
  int_action.sa_handler = sigint_handler;
  sigemptyset(&int_action.sa_mask);
  int_action.sa_flags = SA_RESTART;
  if (sigaction(SIGINT, &int_action, NULL) == -1) {
    perror("sigaction SIGINT");
    return -1;
  }
  */
  return 0;

}

void sigint_handler(int s) { // program shuts down nicely when sigint is received 
  s = s; // suppress compiler warning
  // TODO clean shutdown routine
}

void sigchld_handler(int s)
{
  s = s; // suppress compiler warning
  // waitpid() might overwrite errno, so we save and restore it:
  int saved_errno = errno;

  while(waitpid(-1, NULL, WNOHANG) > 0);

  errno = saved_errno;
}

/*
void *p2p_client(void *err)
// -----------------------------------------------------------------------------
// Func: client thread of peer to peer service. This thread queries new
//       connections for their latest block. If the response is a block with a 
//       higher index than the latest block stored by this node, it will request
//       the chain.
// Args: err - a pointer managed by the dispatcher which is used to store error
//             codes for this thread
// Retn: *(int *)err will be zero unless there has been a fault
// -----------------------------------------------------------------------------
{
  int sockfd, numbytes;
  char buf[100];
  struct addrinfo hints, *servinfo, *p;
  int rv;
  char s[INET6_ADDRSTRLEN];  

  *(int *)err = 0; // this will change in case of errors
  memset(&hints, 0, sizeof hints);
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM;

  // TODO server hostname is currently hardcoded as "server" in 
  // first argument
  if ((rv = getaddrinfo("localhost", port, &hints, &servinfo)) != 0) {
    fprintf(stderr, "p2p_client getaddrinfo: %s\n", gai_strerror(rv));
    *(int *)err = 1;
    pthread_exit(err);
  }

  for (p = servinfo; p != NULL; p = p->ai_next) {
    if ((sockfd = socket(p->ai_family, p->ai_socktype,
      p->ai_protocol)) == -1) {
        perror("p2p_client: socket");
        continue;
      }

    if (connect(sockfd, p->ai_addr, p->ai_addrlen) == -1) {
      close(sockfd);
      perror("p2p_client: connect");
      continue;
    }
    break;
  }

  if (p == NULL) {
    fprintf(stderr, "p2p_client: failed to connect\n");
    *(int *)err = 2;
    pthread_exit(err);
  }

  inet_ntop(p->ai_family, get_in_addr((struct sockaddr *)p->ai_addr),
    s, sizeof s);
  printf("p2p_client: connecting to %s\n", s);

  freeaddrinfo(servinfo);

  if ((numbytes = recv(sockfd, buf, 100-1, 0)) == -1) {
    perror("p2p_client recv");
    exit(1); // fatal
  }

  buf[numbytes] = '\0';

  printf("p2p_client: received'%s'\n", buf);
  close(sockfd);


  pthread_exit(err);
}
*/

int startup(int argc, char *argv[]) 
{
  #ifndef DEBUG
  util_print_license();
  #endif
  if (process_cmd_args(argc, argv)) {
    return 0;
  }
  return 0;
}

int process_cmd_args(int argc, char *argv[]) {
  // check command line arguments
  // right now, if the argument is -h then argv[1][1] will be hashed
  // and the program will exit (for testing hashing)
  if (argc > 1) { // process flags
    if (strlen(argv[1]) == 2 && argv[1][0] == '-') {
      switch (argv[1][1]) {
        case 'h': util_cmd_hash(argv[2]); break;
        default: printf("Command line argument is not recognized\n");
      }
    }
    else {
      printf("Command line argument is malformed\n");
    }
    return 1;
  }

  return 0;
}